### ISSUE TITLE
QgsMessageBar.INFO no longer exist ( QGIS 2.99.0-b6ad920404)

### ISSUE THREAD

**Issue by olivierh65** [borysiasty/plugin_reloader#12]
Hi,
There is an error when pushing the message after plugin reloaded.

To correct:
Add line 24 : 
from qgis.core import Qgis

and change line 124 from
self.iface.messageBar().pushMessage("<b>%s</b> reloaded." % plugin, QgsMessageBar.INFO)
 to : 
self.iface.messageBar().pushMessage("<b>%s</b> reloaded." % plugin, Qgis.Success)

**Comment by HeikkiVesanto** [comment]
Alternatively you can use something like:
self.iface.messageBar().pushInfo("Title", "Message")

For example:
self.iface.messageBar().pushInfo("Success", "<b>%s</b> reloaded." % plugin)

**Comment by borysiasty** [comment]
Thanks guys! I'm waiting for @All4Gis' response and merging it before Friday.

**Comment by All4Gis** [comment]
Hi,What response are you waiting @borysiasty ?This is a simple change #13 and we maintain the warning level using Info and no Succes @olivierh65 and @HeikkiVesanto ,this is a good alternative `self.iface.messageBar().pushInfo("Success", "%s reloaded." % plugin)`
In my opinion, this PR #13  fix this bug making minimum code changes

**Comment by borysiasty** [comment]
@All4Gis: Ah, our lovely Github :) I've pinged you here, suspecting you could not get the notification from the PR. I asked inline: https://github.com/borysiasty/plugin_reloader/pull/13/files

**Comment by All4Gis** [comment]
mmm...I don't see any question,comment etc.
![captura](https://user-images.githubusercontent.com/8123225/36472141-27b333fa-16f1-11e8-9846-e7cf1f88dfe0.PNG) ,it's here?

**Comment by borysiasty** [comment]
Ah, forgot to submit the pending comment. I'm sorry, my fault! Check it now.
In fact it was just one simple question if there was any particular reason for importing it like that.

**Comment by borysiasty** [comment]
Fixed in 1f4293576e204
