### ISSUE TITLE
whatsThis not updating after configure

### ISSUE THREAD

**Issue by raymondnijssen** [borysiasty/plugin_reloader#17]
When I configure the reloader to reload another plugin, the action text is set to: "Reload plugin: <plugin2>" but the whatsThis remains "Reload plugin: <plugin1>". It could however be a qt problem since in the python console

this works:
qgis.utils.plugins['plugin_reloader'].actionRun.setText('test')

and this doesn't:
qgis.utils.plugins['plugin_reloader'].actionRun.setWhatsThis('test')

Anyway, it does load the correct plugin, but it is a bit confusing. I am using qgis 3.3 master on ubuntu 18.04 with qt 5.9.5

**Comment by borysiasty** [comment]
Thanks! Let me fix it when 3.4 is released :)

**Comment by raymondnijssen** [comment]
:+1:

**Comment by borysiasty** [comment]
Fixed by Nyall :)
