### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

### ISSUE THREAD

**Issue by andmichalski** [borysiasty/plugin_reloader#18]
After upgrading to version 3.4 (I am using Ubuntu 18) plugin not reload correctlly. It seems that __init__.py of function was not correctlly running. Eg. combobox of reloaded toolbar are deleted...
Thanks for help.

**Comment by borysiasty** [comment]
Twoja wtyczka musi na wyjściu odłączać sygnały z QGIS-a, które podłączyła przy ładowaniu. Reloader usuwa z pamięci starą instancję i ładuje nową, a nieodłączone sygnały z projektu czy legendy trafiają na takie właśnie puste miejsca po widgetach. Nie musi natomiast odłączać swoich wewnętrznych, skoro obiekt wysyłający idzie do piachu i już nic i tak nie wyśle.

Zamykam, bo Reloader tylko obnaża ten problem, a dokładnie tak samo się stanie, jeśli np. wyłączysz lub odinstalujesz wtyczkę w Menedżerze, po czym QGIS coś do niej wyśle. Więc nawet, gdyby Reloader  jakoś odłączał wszystkie nieodłączone sygnały (co jest prawdopodobnie niemożliwe), to by w ten sposób tylko zachęcał nas do pisania wadliwych wtyczek :)
