### ISSUE TITLE
Fresh plugin in fresh install tries to load an empty plugin

### ISSUE THREAD

**Issue by rduivenvoorde** [borysiasty/plugin_reloader#27]
Not really important because it happens only once :-)

But when you have a fresh install, install another plugin, and the the plugin reloader,
Push the Plugin reloader button in the button bar,
There is (off course) no plugin selected yet, so the following exception is raised:
Would be good to switch to the configuration window when the 'module name' is empty?
(OR initiate it with the Plugin Reloader itself?)

```
2021-10-08T19:11:17     CRITICAL    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
              __import__(packageName)
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ValueError: Empty module name
```          

Super, super needed plugin by the way!!! Thanks!

**Comment by jfbourdon** [comment]
Are you saying that the configuration window is not showing up when following the steps you described? On my machine the same error is raised, but the configuration window pops up at the same time.

It might be better to have a more specific message in the message bar for this special case, but a simpler approach would be to initiate the pluginit with itself as you suggest.

**Comment by borysiasty** [comment]
Hi Richard!
Hopefully it's fixed now. A new version is ready for release, just waiting a bit for a possible translaton update.

**Comment by rduivenvoorde** [comment]
Cool, thanks for taking time! I'll test the next release!

**Comment by borysiasty** [comment]
Not a problem at all. It's my duty to assure that Mankind and all the Aliens are comfortable with reloading their QGIS plugins ;)

**Comment by rduivenvoorde** [comment]
Ok, just tested... Closing
