### ISSUE TITLE
Qt6 :-)

### ISSUE THREAD

**Issue by rduivenvoorde** [borysiasty/plugin_reloader#39]
Dear Borys,

My first Qt6 build of QGIS, first plugin (wel... second) plugin to install is off course the famous plugin reloader...

But not updated for Qt6 yet :-)

I can see if I can make this work (unless you are already on it)..

o/ from The Netherlands!

**Comment by borysiasty** [comment]
Hi Richard! 
I'll look at it this weekend! :)

**Comment by borysiasty** [comment]
Done :)

**Comment by rduivenvoorde** [comment]
Wheeeee, Thanks Borys!

Works!

![Screenshot from 2024-03-09 08-24-48](https://github.com/borysiasty/plugin_reloader/assets/731673/cb7b5a9c-0311-4b36-b45e-87ec94d4055d)

**Comment by borysiasty** [comment]
You're welcome!
