### ISSUE TITLE
The plugin toolbar is now very long in the UI

### ISSUE THREAD

**Issue by Gustry** [borysiasty/plugin_reloader#41]
Due the latest update, the plugin toolbar is very long because it has some text : 

![image](https://github.com/user-attachments/assets/b77b3b31-c934-4425-95a0-331048f8616c)

I was preferring when it was only icon, and no text in my toolbar ;-)

And now, I have twice the icon of the plugin, was-it expected as well ?

**Comment by borysiasty** [comment]
It's for guys working on a dozen plugins at once :)

I'll make the text optional and try to merge the arrow and plugin icon into one pixmap (otherwise it's hard to see what plugin is currently selected). But I'll ask you for a test how it's readable in light and dark color schemes.

**Comment by borysiasty** [comment]
Done. Hopefully the new combined icon is readable somehow. Otherwise I'll have to to make the arrow more brutal.

**Comment by Gustry** [comment]
> It's for guys working on a dozen plugins at once :)

Yes, I could notice this new feature, it's a great improvement !

What about adding a QComboxBox, with autocompletion, in the toolbar ?

**Comment by Gustry** [comment]
Ah, great, we answered at the same time. I will try your new version ASAP ;-)

**Comment by borysiasty** [comment]
Brilliant! With the combobox you can't reload with one click, so it forces folks to let mice alone and start using the shortcut in the end! :D
![](https://c.tenor.com/b-mWVHaNvjAAAAAC/tenor.gif)

Anyway, I've merged and released it without waiting for more ideas to come ;D There was 1800 downloads of that version already, so people will get a liiiiittle bit upset :) 

As you can see, for now it's a QToolButton with dynamic menu, where recently reloaded plugin always goes to the top. I assume we usually work on just a few plugins at once, and this subset slowly changes from week to week.  The button's default action is yet another (and not one of those from the menu), so it's look is tweakable (e.g. it has modified icon with the arrow).
