### ISSUE TITLE
plugin_reloader bug

### ISSUE THREAD

**Issue by drathomas** [borysiasty/plugin_reloader#45]
Dear Borys,
when installing your plugin reloader I received errors in several  files, some related to pseudocode (:=). As a QGIS-python newbie I would love to use your plugin so it would be great if you could fix that!
Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.16-Pi Pi, df27394552 

Cheers Axel

**Comment by borysiasty** [comment]
Hi!
Thanks for raising this issue. The current Reloader requires Python 3.9, while your very very old QGIS uses 3.7.

If you are forced to use such an old version, I believe Reloader 0.9.3 should work with Python 3.7  (if not, please try yet older one). You can download the zip below and install it by the "Install from ZIP" tab in the plugin manager:
https://plugins.qgis.org/plugins/plugin_reloader/version/0.9.3/

Of course, the best would be to upgrade QGIS to some modern version or at least [QGIS-OSGeo4W-3.16.8-4.msi](https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.16.8-4.msi) (assuming you're on Windows), what was the very first version containing Python 3.9 (but note it must be the msi installer and not exe).

**Comment by drathomas** [comment]
Hi Borys,
thanks to your prompt reply. I only recently installed QGIS with an installer that was labelled as the newest release - which it obviously was not. So I am going to upgrade my installation as you propose.
Thanks again!
 
Axel
***@***.***
 


Gesendet: Dienstag, 26. November 2024 um 17:41
Von: "Borys Jurgiel" ***@***.***>
An: borysiasty/plugin_reloader ***@***.***>
CC: drathomas ***@***.***>,Author ***@***.***>
Betreff: Re: [borysiasty/plugin_reloader] plugin_reloader bug (Issue #45)

 
Hi!Thanks for raising this issue. The current Reloader requires Python 3.9, while your very very old QGIS uses 3.7.
If you are forced to use such an old version, I believe Reloader 0.9.3 should work with Python 3.7 (if not, please try yet older one). You can download the zip below and install it by the "Install from ZIP" tab in the plugin manager:https://plugins.qgis.org/plugins/plugin_reloader/version/0.9.3/
Of course, the best would be to upgrade QGIS to some modern version or at least QGIS-OSGeo4W-3.16.8-4.msi (assuming you're on Windows), what was the very first version containing Python 3.9 (but note it must be the msi installer and not exe).

**Comment by drathomas** [comment]
Hi Borys,
I upgraded QGIS via the link you provided. The installation now includes Python 3.9 but installing the Reloader from zip again thorows an error (see below). Any idea what went wrong?
 
Cheers Axel
 

Couldn't load plugin 'plugin_reloader' due to an error when calling its initGui() method 
UnboundLocalError: local variable 'plugins' referenced before assignment 
Traceback (most recent call last):  File "C:\PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 359, in startPlugin    plugins[packageName].initGui()  File "C:\Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plugin_reloader\Plugin.py", line 98, in initGui    for plugin in Settings.recentPlugins():  File "C:\Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plugin_reloader\Settings.py", line 32, in recentPlugins    if plugins == QSettings().value(f'{cls.PREFIX}/recentPlugins', '',UnboundLocalError: local variable 'plugins' referenced before assignment
Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] QGIS version: 3.16.8-Hannover Hannover, 8c50902e 
Python Path:

C:/PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python
C:/Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.16.8\bin\python39.zip
C:\PROGRA~1\QGIS31~1.8\apps\Python39\DLLs
C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib
C:\Program Files\QGIS 3.16.8\bin
C:\PROGRA~1\QGIS31~1.8\apps\Python39
C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\Pythonwin
C:/Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python


***@***.***
 


Gesendet: Dienstag, 26. November 2024 um 17:41
Von: "Borys Jurgiel" ***@***.***>
An: borysiasty/plugin_reloader ***@***.***>
CC: drathomas ***@***.***>,Author ***@***.***>
Betreff: Re: [borysiasty/plugin_reloader] plugin_reloader bug (Issue #45)

 
Hi!Thanks for raising this issue. The current Reloader requires Python 3.9, while your very very old QGIS uses 3.7.
If you are forced to use such an old version, I believe Reloader 0.9.3 should work with Python 3.7 (if not, please try yet older one). You can download the zip below and install it by the "Install from ZIP" tab in the plugin manager:https://plugins.qgis.org/plugins/plugin_reloader/version/0.9.3/
Of course, the best would be to upgrade QGIS to some modern version or at least QGIS-OSGeo4W-3.16.8-4.msi (assuming you're on Windows), what was the very first version containing Python 3.9 (but note it must be the msi installer and not exe).

**Comment by amr66** [comment]
Hey @drathomas, I think you may have misunderstood @borysiasty. 3.16 again is quite old but be able to run the current version, installed by the plugin manager inside QGIS. The plugin_reloader with version 0.9.3 was the last one supporting Python 3.7. Is the any reason why you don't just install the current version of QGIS? It's availabe on their web site. LTR now has 3.34 (I recommend, stable) and the newest is 3.40.

**Comment by borysiasty** [comment]
Exactly. Thanks @amr66!

**Comment by drathomas** [comment]
Thanks - I guess I indeed misunderstood. Will install 3.34.
***@***.***
 


Gesendet: Donnerstag, 28. November 2024 um 15:49
Von: Andreas ***@***.***>
An: borysiasty/plugin_reloader ***@***.***>
CC: drathomas ***@***.***>,Mention ***@***.***>
Betreff: Re: [borysiasty/plugin_reloader] plugin_reloader bug (Issue #45)

 
Hey @drathomas, I think you may have misunderstood @borysiasty. 3.16 again is quite old but be able to run the current version, installed by the plugin manager inside QGIS. The plugin_reloader with version 0.9.3 was the last one supporting Python 3.7. Is the any reason why you don't just install the current version of QGIS? It's availabe on their web site. LTR now has 3.34 (I recommend, stable) and the newest is 3.40.

**Comment by drathomas** [comment]
Hi, installed 3.34.13 but have (almost) the same trouble. I receive the same warning as with the older QGIS versions when installing the plugin, but immediately afterwards the plugin appears to have been installed (Plugin Reloader menu item is visible). 
However, in the Plugins Log Messages windows you find:

2024-12-03T14:00:40     CRITICAL    Traceback (most recent call last):              File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin              plugins[packageName].initGui()              File "C:\Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plugin_reloader\Plugin.py", line 98, in initGui              for plugin in Settings.recentPlugins():              ^^^^^^^^^^^^^^^^^^^^^^^^              File "C:\Users/gisservice/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plugin_reloader\Settings.py", line 32, in recentPlugins              if plugins == QSettings().value(f'{cls.PREFIX}/recentPlugins', '',              ^^^^^^^             UnboundLocalError: cannot access local variable 'plugins' where it is not associated with a value

 
When trying to run the Plugin Reloader nothing happens.
Any ideas how to fix that?
 
Cheers Axel
 
***@***.***
 


Gesendet: Donnerstag, 28. November 2024 um 15:49
Von: Andreas ***@***.***>
An: borysiasty/plugin_reloader ***@***.***>
CC: drathomas ***@***.***>,Mention ***@***.***>
Betreff: Re: [borysiasty/plugin_reloader] plugin_reloader bug (Issue #45)

 
Hey @drathomas, I think you may have misunderstood @borysiasty. 3.16 again is quite old but be able to run the current version, installed by the plugin manager inside QGIS. The plugin_reloader with version 0.9.3 was the last one supporting Python 3.7. Is the any reason why you don't just install the current version of QGIS? It's availabe on their web site. LTR now has 3.34 (I recommend, stable) and the newest is 3.40.

**Comment by borysiasty** [comment]
Looks like you edited the reloader's code trying to fix it. Just go to the Plugin Manager, find the Reloader and click _Reinstall_ to revert your edits: 

![Screenshot_20241203_170209](https://github.com/user-attachments/assets/58edeab1-2b28-4c91-8d45-e63dc72c885d)
