### ISSUE TITLE
Problem with reloading plugins using GDAL

### ISSUE THREAD

**Issue by borysiasty** [borysiasty/plugin_reloader#5]
_Migrated from http://hub.qgis.org/issues/14383
Bug report #14383, added by @erpas, 2016-02-26._

Reloading a Python plugin using GDAL, say GDALTools or Serval, makes it unusable: not functioning or prone to strange errors (). After QGIS is restarted plugins operate normally.

To reproduce it in QGIS 2.12.3 on Debian 8 and on Windows 7 (OSGeo4W 32-bit):
1. Load a raster into QGIS project
2. Try to use one of the GDALTools tools, for example Extraction > Clip - just to check if it works before reloading
3. Reload GDALTools using Plugin Reloader
4. Try to open the tool dialog once again -> nothing happens.

Users normally do not reload plugins, but it can be a problem when a plugin gets an update and is reloaded by Plugin Manager.

**Comment by borysiasty** [comment]
@erpas are you going to rewrite Serval for QGIS 3? Otherwise there is no way to test if it's fixed now, GdalTools are dead.

**Comment by erpas** [comment]
@borysiasty yep, actually, it is being ported already [1]. However, it will no longer use GDAL Python methods for raster modification, but a native `writeBlock` method of [QgsRasterDataProvider](https://qgis.org/api/3.2/classQgsRasterDataProvider.html).

I have just submitted an issue for raster data provider cache being not properly cleared [2] that prevents publishing the QGIS 3 port. Hope it can be sorted easily before the 3.4 is out...

[1] https://github.com/erpas/serval/tree/QGIS_3_port
[2] https://issues.qgis.org/issues/20104
