### ISSUE TITLE
Plugin not showing up in QGIS master plugin manager

### ISSUE THREAD

**Issue by m-kuhn** [borysiasty/plugin_reloader#7]
I was about to upgrade the plugin to QGIS 3.0 compatibility when I noticed, that this has already been done (thanks @3nids). However, it doesn't show up in the plugin manager, is this related to the version code (only 2.99, the other plugins I have don't specify a maximum version)? CC @elpaso

**Comment by elpaso** [comment]
It might be https://github.com/borysiasty/plugin_reloader/blob/master/metadata.txt#L14, see also this: https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/models.py#L497
I think that master now sends version 3.0.

**Comment by borysiasty** [comment]
Hi @m-kuhn, I can't compile master at the moment, but I believe it still sends 2.99.0 (doesn't it?), so could you please try to set:
qgisMinimumVersion=2.99
qgisMaximumVersion=3.99

Maybe there is a bug in the comparison algorithm and the current "2.99.0" is considered > "2.99".

If master is switched to "3.0" we can just set the qgisMinimumVersion to 3.0 and remove qgisMaximumVersion - it will fall back to the default value int(qgisMinimumVersion) + 0.99.

**Comment by m-kuhn** [comment]
i think if you merge #8 it will work. at least with that one it gets picked up by the plugin manager locally.

**Comment by borysiasty** [comment]
@m-kuhn I don't understand why it works ;) so I just changed qgisMax to 3.99 and released it as 0.7.1.
This way it also won't stop working when QGIS declared version is bumped up to 3.0.
Could you please try if it works for you?

**Comment by m-kuhn** [comment]
Works :tada: 
Thanks @borysiasty
